apiVersion: v1
kind: Service
metadata:
  name: keycloak-odf
  labels:
    name: keycloak-odf
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app.kubernetes.io/name: keycloak-odf-app
