apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
name: mysql-grafana-datasource
spec:
datasources:
    - type: mysql
name: MySQL
access: proxy
url: ramendemo-mysql
database: ramendemo
user: ramendemo
password: ramendemo
name: grafana-mysql-datasource.yaml
